<?php
$data = array (
  3 => 
  array (
    'cat_id' => '3',
    'cat_name' => 'SPRING/SUMMER',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '1',
    'has_children' => '4',
    'goods_num' => 0,
    'level' => 0,
    'id' => '3',
    'name' => 'SPRING/SUMMER',
  ),
  12 => 
  array (
    'cat_id' => '12',
    'cat_name' => 'Jackets',
    'measure_unit' => '',
    'parent_id' => '3',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '3',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '12',
    'name' => 'Jackets',
  ),
  11 => 
  array (
    'cat_id' => '11',
    'cat_name' => 'Tops',
    'measure_unit' => '',
    'parent_id' => '3',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '4',
    'has_children' => '0',
    'goods_num' => '3',
    'level' => 1,
    'id' => '11',
    'name' => 'Tops',
  ),
  9 => 
  array (
    'cat_id' => '9',
    'cat_name' => 'Dresses',
    'measure_unit' => '',
    'parent_id' => '3',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '5',
    'has_children' => '0',
    'goods_num' => '1',
    'level' => 1,
    'id' => '9',
    'name' => 'Dresses',
  ),
  10 => 
  array (
    'cat_id' => '10',
    'cat_name' => 'Skirts',
    'measure_unit' => '',
    'parent_id' => '3',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '6',
    'has_children' => '0',
    'goods_num' => '3',
    'level' => 1,
    'id' => '10',
    'name' => 'Skirts',
  ),
  4 => 
  array (
    'cat_id' => '4',
    'cat_name' => 'AUTUMN/WINTER',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '2',
    'has_children' => '3',
    'goods_num' => 0,
    'level' => 0,
    'id' => '4',
    'name' => 'AUTUMN/WINTER',
  ),
  5 => 
  array (
    'cat_id' => '5',
    'cat_name' => 'Dresses',
    'measure_unit' => '',
    'parent_id' => '4',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '7',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '5',
    'name' => 'Dresses',
  ),
  6 => 
  array (
    'cat_id' => '6',
    'cat_name' => 'Tops',
    'measure_unit' => '',
    'parent_id' => '4',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '8',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '6',
    'name' => 'Tops',
  ),
  7 => 
  array (
    'cat_id' => '7',
    'cat_name' => 'Skirts',
    'measure_unit' => '',
    'parent_id' => '4',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '9',
    'has_children' => '0',
    'goods_num' => '1',
    'level' => 1,
    'id' => '7',
    'name' => 'Skirts',
  ),
);
?>